services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    group_add:
      - '105' # https://jellyfin.org/docs/general/post-install/transcoding/hardware-acceleration/
    network_mode: 'host'
    volumes:
      - ${DATA}/jellyfin:/config
      - ${DATA}/jellyfin/cache:/cache
      - type: bind
        source: ${MEDIA}
        target: /media
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    restart: 'unless-stopped'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # hardware acceleration